version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres_internship2025
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - mynetwork

  fastapi_app:
    build: .
    container_name: fastapi_app
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8000"
    networks:
      - mynetwork

volumes:
  pg_data:

networks:
  mynetwork:
    driver: bridge
